/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module and_gate_masked(a0, a1, b0, b1, rN, y0, y1);
  wire _0_;
  wire _1_;
  input a0;
  input a1;
  input b0;
  input b1;
  wire p00;
  wire p01;
  wire p10;
  wire p11;
  input rN;
  output y0;
  output y1;
  assign p00 = a0 & b0;
  assign p01 = a0 & b1;
  assign p10 = a1 & b0;
  assign p11 = a1 & b1;
  assign _0_ = p00 ^ p01;
  assign y0 = _0_ ^ rN;
  assign _1_ = p11 ^ p10;
  assign y1 = _1_ ^ rN;
endmodule

module circuit(clk, a0, a1, b0, b1, rN, y0, y1);
  input a0;
  input a1;
  input b0;
  input b1;
  input clk;
  input rN;
  wire w_y0;
  wire w_y1;
  output y0;
  output y1;
  DFF _0_ (
    .C(clk),
    .D(w_y1),
    .Q(y1)
  );
  DFF _1_ (
    .C(clk),
    .D(w_y0),
    .Q(y0)
  );
  and_gate_masked dut (
    .a0(a0),
    .a1(a1),
    .b0(b0),
    .b1(b1),
    .rN(rN),
    .y0(w_y0),
    .y1(w_y1)
  );
endmodule
