/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module circuit(clk, i_A0, i_A1, i_B0, i_B1, rN, o_sum0, o_sum1, o_carry0, o_carry1);
  wire carry0_w;
  wire carry1_w;
  input clk;
  input i_A0;
  input i_A1;
  input i_B0;
  input i_B1;
  output o_carry0;
  output o_carry1;
  output o_sum0;
  output o_sum1;
  input rN;
  wire sum0_w;
  wire sum1_w;
  DFF _0_ (
    .C(clk),
    .D(sum1_w),
    .Q(o_sum1)
  );
  DFF _1_ (
    .C(clk),
    .D(carry0_w),
    .Q(o_carry0)
  );
  DFF _2_ (
    .C(clk),
    .D(carry1_w),
    .Q(o_carry1)
  );
  DFF _3_ (
    .C(clk),
    .D(sum0_w),
    .Q(o_sum0)
  );
  half_adder_masked dut (
    .A0(i_A0),
    .A1(i_A1),
    .B0(i_B0),
    .B1(i_B1),
    .carry0(carry0_w),
    .carry1(carry1_w),
    .rN(rN),
    .sum0(sum0_w),
    .sum1(sum1_w)
  );
endmodule

module half_adder_masked(A0, A1, B0, B1, rN, sum0, sum1, carry0, carry1);
  wire _00_;
  wire _01_;
  input A0;
  input A1;
  input B0;
  input B1;
  output carry0;
  output carry1;
  wire p00;
  wire p01;
  wire p10;
  wire p11;
  input rN;
  output sum0;
  output sum1;
  wire sum_temp0;
  wire sum_temp1;
  assign sum0 = A0 ^ B0;
  assign sum1 = A1 ^ B1;
  assign p00 = A0 & B0;
  assign p01 = A0 & B1;
  assign p10 = A1 & B0;
  assign p11 = A1 & B1;
  assign _00_ = p00 ^ p01;
  assign carry0 = _00_ ^ rN;
  assign _01_ = p11 ^ p10;
  assign carry1 = _01_ ^ rN;
  assign sum_temp0 = sum0;
  assign sum_temp1 = sum1;
endmodule
