/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module circuit(clk, i_A0, i_A1, i_B0, i_B1, i_C0, i_C1, rN, o_Y0, o_Y1);
  wire Y0_w;
  wire Y1_w;
  input clk;
  input i_A0;
  input i_A1;
  input i_B0;
  input i_B1;
  input i_C0;
  input i_C1;
  output o_Y0;
  output o_Y1;
  input rN;
  DFF _0_ (
    .C(clk),
    .D(Y1_w),
    .Q(o_Y1)
  );
  DFF _1_ (
    .C(clk),
    .D(Y0_w),
    .Q(o_Y0)
  );
  three_input_and_gate_masked dut (
    .A0(i_A0),
    .A1(i_A1),
    .B0(i_B0),
    .B1(i_B1),
    .C0(i_C0),
    .C1(i_C1),
    .Y0(Y0_w),
    .Y1(Y1_w),
    .rN(rN)
  );
endmodule

module three_input_and_gate_masked(A0, A1, B0, B1, C0, C1, rN, Y0, Y1);
  wire _00_;
  wire _01_;
  input A0;
  input A1;
  input B0;
  input B1;
  input C0;
  input C1;
  output Y0;
  output Y1;
  wire c0;
  wire c1;
  wire p00;
  wire p01;
  wire p10;
  wire p11;
  input rN;
  assign p00 = A0 & B0;
  assign p01 = A0 & B1;
  assign p10 = A1 & B0;
  assign p11 = A1 & B1;
  assign _00_ = p00 ^ p01;
  assign c0 = _00_ ^ rN;
  assign _01_ = p11 ^ p10;
  assign c1 = _01_ ^ rN;
  assign Y0 = c0 & C0;
  assign Y1 = c1 & C1;
endmodule
