/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module circuit(clk, i_a0, i_a1, i_b0, i_b1, r0, r1, o_sum0, o_sum1, o_carry0, o_carry1);
  wire carry0_w;
  wire carry1_w;
  input clk;
  input i_a0;
  input i_a1;
  input i_b0;
  input i_b1;
  output o_carry0;
  output o_carry1;
  output o_sum0;
  output o_sum1;
  input r0;
  input r1;
  wire sum0_w;
  wire sum1_w;
  DFF _0_ (
    .C(clk),
    .D(sum1_w),
    .Q(o_sum1)
  );
  DFF _1_ (
    .C(clk),
    .D(carry0_w),
    .Q(o_carry0)
  );
  DFF _2_ (
    .C(clk),
    .D(carry1_w),
    .Q(o_carry1)
  );
  DFF _3_ (
    .C(clk),
    .D(sum0_w),
    .Q(o_sum0)
  );
  half_adder_masked dut (
    .a0(i_a0),
    .a1(i_a1),
    .b0(i_b0),
    .b1(i_b1),
    .carry0(carry0_w),
    .carry1(carry1_w),
    .r0(r0),
    .r1(r1),
    .sum0(sum0_w),
    .sum1(sum1_w)
  );
endmodule

module half_adder_masked(a0, a1, b0, b1, r0, r1, sum0, sum1, carry0, carry1);
  wire _00_;
  wire _01_;
  input a0;
  input a1;
  input b0;
  input b1;
  output carry0;
  output carry1;
  wire p00;
  wire p01;
  wire p10;
  wire p11;
  input r0;
  input r1;
  output sum0;
  output sum1;
  assign sum0 = a0 ^ b0;
  assign sum1 = a1 ^ b1;
  assign p00 = a0 & b0;
  assign p01 = a0 & b1;
  assign p10 = a1 & b0;
  assign p11 = a1 & b1;
  assign _00_ = p00 ^ p01;
  assign carry0 = _00_ ^ r0;
  assign _01_ = p11 ^ p10;
  assign carry1 = _01_ ^ r1;
endmodule
