/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module black_masked(i_pj0, i_pj1, i_gj0, i_gj1, i_pk0, i_pk1, i_gk0, i_gk1, r0, r1, r2, o_g0, o_g1, o_p0, o_p1);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  input i_gj0;
  input i_gj1;
  input i_gk0;
  input i_gk1;
  input i_pj0;
  input i_pj1;
  input i_pk0;
  input i_pk1;
  output o_g0;
  output o_g1;
  output o_p0;
  output o_p1;
  wire p_out_0;
  wire p_out_1;
  input r0;
  input r1;
  input r2;
  wire t1_0;
  wire t1_1;
  wire t2_0;
  wire t2_1;
  wire w1_p00;
  wire w1_p01;
  wire w1_p10;
  wire w1_p11;
  wire w2_p00;
  wire w2_p01;
  wire w2_p10;
  wire w2_p11;
  wire w3_p00;
  wire w3_p01;
  wire w3_p10;
  wire w3_p11;
  assign w3_p10 = i_pk1 & i_pj0;
  assign w3_p11 = i_pk1 & i_pj1;
  assign _04_ = w3_p00 ^ w3_p01;
  assign o_p0 = _04_ ^ r2;
  assign _05_ = w3_p11 ^ w3_p10;
  assign o_p1 = _05_ ^ r2;
  assign _06_ = i_gk0 ^ t1_0;
  assign o_g0 = _06_ ^ t2_0;
  assign _07_ = i_gk1 ^ t1_1;
  assign o_g1 = _07_ ^ t2_1;
  assign w1_p00 = i_gj0 & i_pk0;
  assign w1_p01 = i_gj0 & i_pk1;
  assign w1_p10 = i_gj1 & i_pk0;
  assign w1_p11 = i_gj1 & i_pk1;
  assign _00_ = w1_p00 ^ w1_p01;
  assign t1_0 = _00_ ^ r0;
  assign _01_ = w1_p11 ^ w1_p10;
  assign t1_1 = _01_ ^ r0;
  assign w2_p00 = i_gk0 & t1_0;
  assign w2_p01 = i_gk0 & t1_1;
  assign w2_p10 = i_gk1 & t1_0;
  assign w2_p11 = i_gk1 & t1_1;
  assign _02_ = w2_p00 ^ w2_p01;
  assign t2_0 = _02_ ^ r1;
  assign _03_ = w2_p11 ^ w2_p10;
  assign t2_1 = _03_ ^ r1;
  assign w3_p00 = i_pk0 & i_pj0;
  assign w3_p01 = i_pk0 & i_pj1;
  assign p_out_0 = o_p0;
  assign p_out_1 = o_p1;
endmodule

module circuit(clk, i_pj0, i_pj1, i_gj0, i_gj1, i_pk0, i_pk1, i_gk0, i_gk1, r0, r1, r2, o_g0, o_g1, o_p0, o_p1);
  input clk;
  input i_gj0;
  input i_gj1;
  input i_gk0;
  input i_gk1;
  input i_pj0;
  input i_pj1;
  input i_pk0;
  input i_pk1;
  output o_g0;
  wire o_g0_w;
  output o_g1;
  wire o_g1_w;
  output o_p0;
  wire o_p0_w;
  output o_p1;
  wire o_p1_w;
  input r0;
  input r1;
  input r2;
  DFF _0_ (
    .C(clk),
    .D(o_g1_w),
    .Q(o_g1)
  );
  DFF _1_ (
    .C(clk),
    .D(o_p0_w),
    .Q(o_p0)
  );
  DFF _2_ (
    .C(clk),
    .D(o_p1_w),
    .Q(o_p1)
  );
  DFF _3_ (
    .C(clk),
    .D(o_g0_w),
    .Q(o_g0)
  );
  black_masked dut (
    .i_gj0(i_gj0),
    .i_gj1(i_gj1),
    .i_gk0(i_gk0),
    .i_gk1(i_gk1),
    .i_pj0(i_pj0),
    .i_pj1(i_pj1),
    .i_pk0(i_pk0),
    .i_pk1(i_pk1),
    .o_g0(o_g0_w),
    .o_g1(o_g1_w),
    .o_p0(o_p0_w),
    .o_p1(o_p1_w),
    .r0(r0),
    .r1(r1),
    .r2(r2)
  );
endmodule
