/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module SystemX_masked(F0, F1, A0, A1, B0, B1, C0, C1, r0, r1, r2, r3, r4, r5, r6, r7);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  input A0;
  input A1;
  wire An0;
  wire An1;
  input B0;
  input B1;
  wire Bn0;
  wire Bn1;
  input C0;
  input C1;
  wire Cn0;
  wire Cn1;
  output F0;
  output F1;
  wire e0;
  wire e1;
  wire e_p00_0;
  wire e_p01_0;
  wire e_p10_0;
  wire e_p11_0;
  wire f0;
  wire f1;
  wire f_p00_2;
  wire f_p01_2;
  wire f_p10_2;
  wire f_p11_2;
  wire fand0;
  wire fand1;
  wire fand_p00_7;
  wire fand_p01_7;
  wire fand_p10_7;
  wire fand_p11_7;
  wire g0;
  wire g1;
  wire g_p00_4;
  wire g_p01_4;
  wire g_p10_4;
  wire g_p11_4;
  wire m0_0;
  wire m0_1;
  wire m0_p00_1;
  wire m0_p01_1;
  wire m0_p10_1;
  wire m0_p11_1;
  wire m2_0;
  wire m2_1;
  wire m2_p00_3;
  wire m2_p01_3;
  wire m2_p10_3;
  wire m2_p11_3;
  wire m6_0;
  wire m6_1;
  wire m6_p00_5;
  wire m6_p01_5;
  wire m6_p10_5;
  wire m6_p11_5;
  input r0;
  input r1;
  input r2;
  input r3;
  input r4;
  input r5;
  input r6;
  input r7;
  wire t1_0;
  wire t1_1;
  wire tand0;
  wire tand1;
  wire tand_p00_6;
  wire tand_p01_6;
  wire tand_p10_6;
  wire tand_p11_6;
  assign An0 = ~A0;
  assign An1 = ~A1;
  assign Bn0 = ~B0;
  assign Bn1 = ~B1;
  assign Cn0 = ~C0;
  assign Cn1 = ~C1;
  assign e_p00_0 = An0 & Bn0;
  assign e_p01_0 = An0 & Bn1;
  assign e_p10_0 = An1 & Bn0;
  assign e_p11_0 = An1 & Bn1;
  assign _10_ = e_p00_0 ^ e_p01_0;
  assign e0 = _10_ ^ r0;
  assign _11_ = e_p11_0 ^ e_p10_0;
  assign e1 = _11_ ^ r0;
  assign m0_p00_1 = e0 & Cn0;
  assign m0_p01_1 = e0 & Cn1;
  assign m0_p10_1 = e1 & Cn0;
  assign m0_p11_1 = e1 & Cn1;
  assign _12_ = m0_p00_1 ^ m0_p01_1;
  assign m0_0 = _12_ ^ r1;
  assign _13_ = m0_p11_1 ^ m0_p10_1;
  assign m0_1 = _13_ ^ r1;
  assign f_p00_2 = An0 & B0;
  assign f_p01_2 = An0 & B1;
  assign f_p10_2 = An1 & B0;
  assign f_p11_2 = An1 & B1;
  assign _14_ = f_p00_2 ^ f_p01_2;
  assign f0 = _14_ ^ r2;
  assign _15_ = f_p11_2 ^ f_p10_2;
  assign f1 = _15_ ^ r2;
  assign m2_p00_3 = f0 & Cn0;
  assign m2_p01_3 = f0 & Cn1;
  assign m2_p10_3 = f1 & Cn0;
  assign m2_p11_3 = f1 & Cn1;
  assign _16_ = m2_p00_3 ^ m2_p01_3;
  assign m2_0 = _16_ ^ r3;
  assign _17_ = m2_p11_3 ^ m2_p10_3;
  assign m2_1 = _17_ ^ r3;
  assign g_p00_4 = A0 & B0;
  assign g_p01_4 = A0 & B1;
  assign g_p10_4 = A1 & B0;
  assign g_p11_4 = A1 & B1;
  assign _18_ = g_p00_4 ^ g_p01_4;
  assign g0 = _18_ ^ r4;
  assign _19_ = g_p11_4 ^ g_p10_4;
  assign g1 = _19_ ^ r4;
  assign m6_p00_5 = g0 & Cn0;
  assign m6_p01_5 = g0 & Cn1;
  assign m6_p10_5 = g1 & Cn0;
  assign m6_p11_5 = g1 & Cn1;
  assign _00_ = m6_p00_5 ^ m6_p01_5;
  assign m6_0 = _00_ ^ r5;
  assign _01_ = m6_p11_5 ^ m6_p10_5;
  assign m6_1 = _01_ ^ r5;
  assign tand_p00_6 = m0_0 & m2_0;
  assign tand_p01_6 = m0_0 & m2_1;
  assign tand_p10_6 = m0_1 & m2_0;
  assign tand_p11_6 = m0_1 & m2_1;
  assign _02_ = tand_p00_6 ^ tand_p01_6;
  assign tand0 = _02_ ^ r6;
  assign _03_ = tand_p11_6 ^ tand_p10_6;
  assign tand1 = _03_ ^ r6;
  assign _04_ = m0_0 ^ m2_0;
  assign t1_0 = _04_ ^ tand0;
  assign _05_ = m0_1 ^ m2_1;
  assign t1_1 = _05_ ^ tand1;
  assign fand_p00_7 = t1_0 & m6_0;
  assign fand_p01_7 = t1_0 & m6_1;
  assign fand_p10_7 = t1_1 & m6_0;
  assign fand_p11_7 = t1_1 & m6_1;
  assign _06_ = fand_p00_7 ^ fand_p01_7;
  assign fand0 = _06_ ^ r7;
  assign _07_ = fand_p11_7 ^ fand_p10_7;
  assign fand1 = _07_ ^ r7;
  assign _08_ = t1_0 ^ m6_0;
  assign F0 = _08_ ^ fand0;
  assign _09_ = t1_1 ^ m6_1;
  assign F1 = _09_ ^ fand1;
endmodule

module circuit(clk, A0, A1, B0, B1, C0, C1, r0, r1, r2, r3, r4, r5, r6, r7, F0, F1);
  input A0;
  input A1;
  input B0;
  input B1;
  input C0;
  input C1;
  output F0;
  wire F0_w;
  output F1;
  wire F1_w;
  input clk;
  input r0;
  input r1;
  input r2;
  input r3;
  input r4;
  input r5;
  input r6;
  input r7;
  DFF _0_ (
    .C(clk),
    .D(F1_w),
    .Q(F1)
  );
  DFF _1_ (
    .C(clk),
    .D(F0_w),
    .Q(F0)
  );
  SystemX_masked dut (
    .A0(A0),
    .A1(A1),
    .B0(B0),
    .B1(B1),
    .C0(C0),
    .C1(C1),
    .F0(F0_w),
    .F1(F1_w),
    .r0(r0),
    .r1(r1),
    .r2(r2),
    .r3(r3),
    .r4(r4),
    .r5(r5),
    .r6(r6),
    .r7(r7)
  );
endmodule
