/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module circuit(clk, i_A0, i_A1, i_B0, i_B1, i_C0, i_C1, rN, o_out0, o_out1);
  input clk;
  input i_A0;
  input i_A1;
  input i_B0;
  input i_B1;
  input i_C0;
  input i_C1;
  output o_out0;
  output o_out1;
  wire out0_w;
  wire out1_w;
  input rN;
  DFF _0_ (
    .C(clk),
    .D(out1_w),
    .Q(o_out1)
  );
  DFF _1_ (
    .C(clk),
    .D(out0_w),
    .Q(o_out0)
  );
  three_input_and_gate_masked dut (
    .A0(i_A0),
    .A1(i_A1),
    .B0(i_B0),
    .B1(i_B1),
    .C0(i_C0),
    .C1(i_C1),
    .out0(out0_w),
    .out1(out1_w),
    .rN(rN)
  );
endmodule

module three_input_and_gate_masked(A0, A1, B0, B1, C0, C1, rN, out0, out1);
  wire _00_;
  wire _01_;
  input A0;
  input A1;
  input B0;
  input B1;
  input C0;
  input C1;
  output out0;
  output out1;
  wire p00;
  wire p01;
  wire p10;
  wire p11;
  wire p20;
  wire p21;
  wire p30;
  wire p31;
  input rN;
  assign p00 = A0 & B0;
  assign p01 = A0 & B1;
  assign p10 = A1 & B0;
  assign p11 = A1 & B1;
  assign p20 = p00 & C0;
  assign p21 = p01 & C0;
  assign p30 = p10 & C0;
  assign p31 = p11 & C0;
  assign _00_ = p20 ^ p21;
  assign out0 = _00_ ^ rN;
  assign _01_ = p30 ^ p31;
  assign out1 = _01_ ^ rN;
endmodule
