/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module circuit(clk, i_a0, i_a1, i_b0, i_b1, i_c0, i_c1, rN0, rN1, o_out0, o_out1);
  input clk;
  input i_a0;
  input i_a1;
  input i_b0;
  input i_b1;
  input i_c0;
  input i_c1;
  output o_out0;
  output o_out1;
  wire out0_w;
  wire out1_w;
  input rN0;
  input rN1;
  DFF _0_ (
    .C(clk),
    .D(out1_w),
    .Q(o_out1)
  );
  DFF _1_ (
    .C(clk),
    .D(out0_w),
    .Q(o_out0)
  );
  three_input_and_gate_masked dut (
    .a0(i_a0),
    .a1(i_a1),
    .b0(i_b0),
    .b1(i_b1),
    .c0(i_c0),
    .c1(i_c1),
    .out0(out0_w),
    .out1(out1_w),
    .rN0(rN0),
    .rN1(rN1)
  );
endmodule

module three_input_and_gate_masked(a0, a1, b0, b1, c0, c1, rN0, rN1, out0, out1);
  wire _00_;
  wire _01_;
  input a0;
  input a1;
  input b0;
  input b1;
  input c0;
  input c1;
  output out0;
  output out1;
  wire p00;
  wire p01;
  wire p10;
  wire p11;
  wire p20;
  wire p21;
  wire p30;
  wire p31;
  input rN0;
  input rN1;
  assign p00 = a0 & b0;
  assign p01 = a0 & b1;
  assign p10 = a1 & b0;
  assign p11 = a1 & b1;
  assign p20 = p00 & c0;
  assign p21 = p01 & c0;
  assign p30 = p10 & c1;
  assign p31 = p11 & c1;
  assign _00_ = p20 ^ p21;
  assign out0 = _00_ ^ rN0;
  assign _01_ = p31 ^ p30;
  assign out1 = _01_ ^ rN1;
endmodule
