/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module circuit(clk, too_cold0, too_cold1, too_hot0, too_hot1, mode0, mode1, fan_on0, fan_on1, r0, r1, r2, r3, heater0, heater1, aircon0, aircon1, fan0, fan1);
  output aircon0;
  wire aircon0_w;
  output aircon1;
  wire aircon1_w;
  input clk;
  output fan0;
  wire fan0_w;
  output fan1;
  wire fan1_w;
  input fan_on0;
  input fan_on1;
  output heater0;
  wire heater0_w;
  output heater1;
  wire heater1_w;
  input mode0;
  input mode1;
  input r0;
  input r1;
  input r2;
  input r3;
  input too_cold0;
  input too_cold1;
  input too_hot0;
  input too_hot1;
  DFF _0_ (
    .C(clk),
    .D(heater1_w),
    .Q(heater1)
  );
  DFF _1_ (
    .C(clk),
    .D(aircon0_w),
    .Q(aircon0)
  );
  DFF _2_ (
    .C(clk),
    .D(aircon1_w),
    .Q(aircon1)
  );
  DFF _3_ (
    .C(clk),
    .D(fan1_w),
    .Q(fan1)
  );
  DFF _4_ (
    .C(clk),
    .D(heater0_w),
    .Q(heater0)
  );
  DFF _5_ (
    .C(clk),
    .D(fan0_w),
    .Q(fan0)
  );
  top_module_masked dut (
    .aircon0(aircon0_w),
    .aircon1(aircon1_w),
    .fan0(fan0_w),
    .fan1(fan1_w),
    .fan_on0(fan_on0),
    .fan_on1(fan_on1),
    .heater0(heater0_w),
    .heater1(heater1_w),
    .mode0(mode0),
    .mode1(mode1),
    .r0(r0),
    .r1(r1),
    .r2(r2),
    .r3(r3),
    .too_cold0(too_cold0),
    .too_cold1(too_cold1),
    .too_hot0(too_hot0),
    .too_hot1(too_hot1)
  );
endmodule

module top_module_masked(too_cold0, too_cold1, too_hot0, too_hot1, mode0, mode1, fan_on0, fan_on1, r0, r1, r2, r3, heater0, heater1, aircon0, aircon1, fan0, fan1);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire a_sh0;
  wire a_sh1;
  output aircon0;
  output aircon1;
  output fan0;
  output fan1;
  input fan_on0;
  input fan_on1;
  wire fan_sh0;
  wire fan_sh1;
  wire h_sh0;
  wire h_sh1;
  wire ha_and0;
  wire ha_and1;
  output heater0;
  output heater1;
  input mode0;
  input mode1;
  wire not_mode0;
  wire not_mode1;
  wire p00_0;
  wire p00_1;
  wire p00_2;
  wire p00_3;
  wire p01_0;
  wire p01_1;
  wire p01_2;
  wire p01_3;
  wire p10_0;
  wire p10_1;
  wire p10_2;
  wire p10_3;
  wire p11_0;
  wire p11_1;
  wire p11_2;
  wire p11_3;
  input r0;
  input r1;
  input r2;
  input r3;
  wire t1_0;
  wire t1_1;
  wire t1f_and0;
  wire t1f_and1;
  input too_cold0;
  input too_cold1;
  input too_hot0;
  input too_hot1;
  assign not_mode0 = ~mode0;
  assign not_mode1 = ~mode1;
  assign p00_0 = mode0 & too_cold0;
  assign p01_0 = mode0 & too_cold1;
  assign p10_0 = mode1 & too_cold0;
  assign p11_0 = mode1 & too_cold1;
  assign _00_ = p00_0 ^ p01_0;
  assign h_sh0 = _00_ ^ r0;
  assign _01_ = p11_0 ^ p10_0;
  assign h_sh1 = _01_ ^ r0;
  assign p00_1 = not_mode0 & too_hot0;
  assign p01_1 = not_mode0 & too_hot1;
  assign p10_1 = not_mode1 & too_hot0;
  assign p11_1 = not_mode1 & too_hot1;
  assign _02_ = p00_1 ^ p01_1;
  assign a_sh0 = _02_ ^ r1;
  assign _03_ = p11_1 ^ p10_1;
  assign a_sh1 = _03_ ^ r1;
  assign p00_2 = h_sh0 & a_sh0;
  assign p01_2 = h_sh0 & a_sh1;
  assign p10_2 = h_sh1 & a_sh0;
  assign p11_2 = h_sh1 & a_sh1;
  assign _04_ = p00_2 ^ p01_2;
  assign ha_and0 = _04_ ^ r2;
  assign _05_ = p11_2 ^ p10_2;
  assign ha_and1 = _05_ ^ r2;
  assign _06_ = h_sh0 ^ a_sh0;
  assign t1_0 = _06_ ^ ha_and0;
  assign _07_ = h_sh1 ^ a_sh1;
  assign t1_1 = _07_ ^ ha_and1;
  assign p00_3 = t1_0 & fan_on0;
  assign p01_3 = t1_0 & fan_on1;
  assign p10_3 = t1_1 & fan_on0;
  assign p11_3 = t1_1 & fan_on1;
  assign _08_ = p00_3 ^ p01_3;
  assign t1f_and0 = _08_ ^ r3;
  assign _09_ = p11_3 ^ p10_3;
  assign t1f_and1 = _09_ ^ r3;
  assign _10_ = t1_0 ^ fan_on0;
  assign fan0 = _10_ ^ t1f_and0;
  assign _11_ = t1_1 ^ fan_on1;
  assign fan1 = _11_ ^ t1f_and1;
  assign aircon0 = a_sh0;
  assign aircon1 = a_sh1;
  assign fan_sh0 = fan0;
  assign fan_sh1 = fan1;
  assign heater0 = h_sh0;
  assign heater1 = h_sh1;
endmodule
