/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module circuit(clk, i_a, i_b, o_p, o_g);
  input clk;
  input i_a;
  input i_b;
  output o_g;
  output o_p;
  pg_unmasked uut (
    .clk(clk),
    .i_a(i_a),
    .i_b(i_b),
    .o_g(o_g),
    .o_p(o_p)
  );
endmodule

module pg_unmasked(clk, i_a, i_b, o_p, o_g);
  input clk;
  wire g;
  input i_a;
  input i_b;
  output o_g;
  output o_p;
  wire p;
  DFF _0_ (
    .C(clk),
    .D(p),
    .Q(o_p)
  );
  DFF _1_ (
    .C(clk),
    .D(g),
    .Q(o_g)
  );
  assign p = i_a ^ i_b;
  assign g = i_a & i_b;
endmodule
