/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module XOR_TransmissionGate_masked(A0, A1, B0, B1, r0, r1, r2, XOR0, XOR1);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  input A0;
  input A1;
  input B0;
  input B1;
  output XOR0;
  output XOR1;
  wire notA0;
  wire notA1;
  wire notB0;
  wire notB1;
  wire p_tga00;
  wire p_tga01;
  wire p_tga10;
  wire p_tga11;
  wire p_tgb00;
  wire p_tgb01;
  wire p_tgb10;
  wire p_tgb11;
  wire p_tt00;
  wire p_tt01;
  wire p_tt10;
  wire p_tt11;
  input r0;
  input r1;
  input r2;
  wire tga0;
  wire tga1;
  wire tgb0;
  wire tgb1;
  wire tt0;
  wire tt1;
  assign notA0 = ~A0;
  assign notA1 = ~A1;
  assign notB0 = ~B0;
  assign notB1 = ~B1;
  assign _03_ = p_tgb11 ^ p_tgb10;
  assign tgb1 = _03_ ^ r1;
  assign p_tt00 = tga0 & tgb0;
  assign p_tt01 = tga0 & tgb1;
  assign p_tt10 = tga1 & tgb0;
  assign p_tt11 = tga1 & tgb1;
  assign _04_ = p_tt00 ^ p_tt01;
  assign tt0 = _04_ ^ r2;
  assign _05_ = p_tt11 ^ p_tt10;
  assign tt1 = _05_ ^ r2;
  assign _06_ = tga0 ^ tgb0;
  assign XOR0 = _06_ ^ tt0;
  assign _07_ = tga1 ^ tgb1;
  assign XOR1 = _07_ ^ tt1;
  assign p_tga00 = A0 & notB0;
  assign p_tga01 = A0 & notB1;
  assign p_tga10 = A1 & notB0;
  assign p_tga11 = A1 & notB1;
  assign _00_ = p_tga00 ^ p_tga01;
  assign tga0 = _00_ ^ r0;
  assign _01_ = p_tga11 ^ p_tga10;
  assign tga1 = _01_ ^ r0;
  assign p_tgb00 = notA0 & B0;
  assign p_tgb01 = notA0 & B1;
  assign p_tgb10 = notA1 & B0;
  assign p_tgb11 = notA1 & B1;
  assign _02_ = p_tgb00 ^ p_tgb01;
  assign tgb0 = _02_ ^ r1;
endmodule

module circuit(clk, A0, A1, B0, B1, r0, r1, r2, XOR0, XOR1);
  input A0;
  input A1;
  input B0;
  input B1;
  output XOR0;
  wire XOR0_w;
  output XOR1;
  wire XOR1_w;
  input clk;
  input r0;
  input r1;
  input r2;
  DFF _0_ (
    .C(clk),
    .D(XOR1_w),
    .Q(XOR1)
  );
  DFF _1_ (
    .C(clk),
    .D(XOR0_w),
    .Q(XOR0)
  );
  XOR_TransmissionGate_masked dut (
    .A0(A0),
    .A1(A1),
    .B0(B0),
    .B1(B1),
    .XOR0(XOR0_w),
    .XOR1(XOR1_w),
    .r0(r0),
    .r1(r1),
    .r2(r2)
  );
endmodule
