/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module and_gate_masked(clk, a0, a1, b0, b1, rN, y0, y1);
  wire _00_;
  wire _01_;
  input a0;
  input a1;
  input b0;
  input b1;
  input clk;
  wire p00;
  wire p01;
  wire p10;
  wire p11;
  input rN;
  output y0;
  wire y0_next;
  output y1;
  wire y1_next;
  DFF _02_ (
    .C(clk),
    .D(y1_next),
    .Q(y1)
  );
  DFF _03_ (
    .C(clk),
    .D(y0_next),
    .Q(y0)
  );
  assign p00 = a0 & b0;
  assign p01 = a0 & b1;
  assign p10 = a1 & b0;
  assign p11 = a1 & b1;
  assign _00_ = p00 ^ p01;
  assign y0_next = _00_ ^ rN;
  assign _01_ = p11 ^ p10;
  assign y1_next = _01_ ^ rN;
endmodule

module circuit(clk, a0, a1, b0, b1, rN, y0, y1);
  input a0;
  input a1;
  input b0;
  input b1;
  input clk;
  input rN;
  output y0;
  output y1;
  and_gate_masked dut (
    .a0(a0),
    .a1(a1),
    .b0(b0),
    .b1(b1),
    .clk(clk),
    .rN(rN),
    .y0(y0),
    .y1(y1)
  );
endmodule
