/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module circuit(clk, A0, A1, B0, B1, r0, r1, r2, XOR0, XOR1);
  input A0;
  input A1;
  input B0;
  input B1;
  output XOR0;
  wire XOR0_w;
  output XOR1;
  wire XOR1_w;
  input clk;
  input r0;
  input r1;
  input r2;
  DFF _0_ (
    .C(clk),
    .D(XOR1_w),
    .Q(XOR1)
  );
  DFF _1_ (
    .C(clk),
    .D(XOR0_w),
    .Q(XOR0)
  );
  xor_gate_using_transmission_gates_masked uut (
    .A0(A0),
    .A1(A1),
    .B0(B0),
    .B1(B1),
    .XOR0(XOR0_w),
    .XOR1(XOR1_w),
    .r0(r0),
    .r1(r1),
    .r2(r2)
  );
endmodule

module xor_gate_using_transmission_gates_masked(A0, A1, B0, B1, r0, r1, r2, XOR0, XOR1);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  input A0;
  input A1;
  wire AB0;
  wire AB1;
  wire A_B0;
  wire A_B1;
  wire A_bar0;
  wire A_bar1;
  input B0;
  input B1;
  wire B_bar0;
  wire B_bar1;
  wire T0;
  wire T1;
  output XOR0;
  output XOR1;
  wire p_a_b_00;
  wire p_a_b_01;
  wire p_a_b_10;
  wire p_a_b_11;
  wire p_ab_00;
  wire p_ab_01;
  wire p_ab_10;
  wire p_ab_11;
  wire p_t_00;
  wire p_t_01;
  wire p_t_10;
  wire p_t_11;
  input r0;
  input r1;
  input r2;
  assign A_bar0 = ~A0;
  assign A_bar1 = ~A1;
  assign B_bar0 = ~B0;
  assign B_bar1 = ~B1;
  assign _03_ = p_a_b_11 ^ p_a_b_10;
  assign A_B1 = _03_ ^ r1;
  assign p_t_00 = AB0 & A_B0;
  assign p_t_01 = AB0 & A_B1;
  assign p_t_10 = AB1 & A_B0;
  assign p_t_11 = AB1 & A_B1;
  assign _04_ = p_t_00 ^ p_t_01;
  assign T0 = _04_ ^ r2;
  assign _05_ = p_t_11 ^ p_t_10;
  assign T1 = _05_ ^ r2;
  assign _06_ = AB0 ^ A_B0;
  assign XOR0 = _06_ ^ T0;
  assign _07_ = AB1 ^ A_B1;
  assign XOR1 = _07_ ^ T1;
  assign p_ab_00 = A0 & B_bar0;
  assign p_ab_01 = A0 & B_bar1;
  assign p_ab_10 = A1 & B_bar0;
  assign p_ab_11 = A1 & B_bar1;
  assign _00_ = p_ab_00 ^ p_ab_01;
  assign AB0 = _00_ ^ r0;
  assign _01_ = p_ab_11 ^ p_ab_10;
  assign AB1 = _01_ ^ r0;
  assign p_a_b_00 = A_bar0 & B0;
  assign p_a_b_01 = A_bar0 & B1;
  assign p_a_b_10 = A_bar1 & B0;
  assign p_a_b_11 = A_bar1 & B1;
  assign _02_ = p_a_b_00 ^ p_a_b_01;
  assign A_B0 = _02_ ^ r1;
endmodule
