/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module AND_gate_masked(a0, a1, b0, b1, rN, y0, y1);
  wire _0_;
  wire _1_;
  input a0;
  input a1;
  input b0;
  input b1;
  wire p00;
  wire p01;
  wire p10;
  wire p11;
  input rN;
  output y0;
  output y1;
  assign p00 = a0 & b0;
  assign p01 = a0 & b1;
  assign p10 = a1 & b0;
  assign p11 = a1 & b1;
  assign _0_ = p00 ^ p01;
  assign y0 = _0_ ^ rN;
  assign _1_ = p11 ^ p10;
  assign y1 = _1_ ^ rN;
endmodule

module circuit(clk, i_a0, i_a1, i_b0, i_b1, rN, o_y0, o_y1);
  input clk;
  input i_a0;
  input i_a1;
  input i_b0;
  input i_b1;
  output o_y0;
  output o_y1;
  input rN;
  wire y0_w;
  wire y1_w;
  DFF _0_ (
    .C(clk),
    .D(y1_w),
    .Q(o_y1)
  );
  DFF _1_ (
    .C(clk),
    .D(y0_w),
    .Q(o_y0)
  );
  AND_gate_masked dut (
    .a0(i_a0),
    .a1(i_a1),
    .b0(i_b0),
    .b1(i_b1),
    .rN(rN),
    .y0(y0_w),
    .y1(y1_w)
  );
endmodule
