/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module circuit(clk, a0, a1, b0, b1, c0, c1, d0, d1, r0, r1, r2, out0, out1, out_n0, out_n1);
  input a0;
  input a1;
  input b0;
  input b1;
  input c0;
  input c1;
  input clk;
  input d0;
  input d1;
  output out0;
  wire out0_w;
  output out1;
  wire out1_w;
  output out_n0;
  wire out_n0_w;
  output out_n1;
  wire out_n1_w;
  input r0;
  input r1;
  input r2;
  DFF _0_ (
    .C(clk),
    .D(out1_w),
    .Q(out1)
  );
  DFF _1_ (
    .C(clk),
    .D(out_n0_w),
    .Q(out_n0)
  );
  DFF _2_ (
    .C(clk),
    .D(out_n1_w),
    .Q(out_n1)
  );
  DFF _3_ (
    .C(clk),
    .D(out0_w),
    .Q(out0)
  );
  top_module_masked dut (
    .a0(a0),
    .a1(a1),
    .b0(b0),
    .b1(b1),
    .c0(c0),
    .c1(c1),
    .d0(d0),
    .d1(d1),
    .out0(out0_w),
    .out1(out1_w),
    .out_n0(out_n0_w),
    .out_n1(out_n1_w),
    .r0(r0),
    .r1(r1),
    .r2(r2)
  );
endmodule

module top_module_masked(a0, a1, b0, b1, c0, c1, d0, d1, r0, r1, r2, out0, out1, out_n0, out_n1);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  input a0;
  input a1;
  wire ab0;
  wire ab1;
  wire abcd0;
  wire abcd1;
  wire and_ab_cd_0;
  wire and_ab_cd_1;
  input b0;
  input b1;
  input c0;
  input c1;
  wire cd0;
  wire cd1;
  input d0;
  input d1;
  output out0;
  output out1;
  output out_n0;
  output out_n1;
  wire p00_ab;
  wire p00_abcd_and;
  wire p00_cd;
  wire p01_ab;
  wire p01_abcd_and;
  wire p01_cd;
  wire p10_ab;
  wire p10_abcd_and;
  wire p10_cd;
  wire p11_ab;
  wire p11_abcd_and;
  wire p11_cd;
  input r0;
  input r1;
  input r2;
  assign out_n0 = ~abcd0;
  assign out_n1 = ~abcd1;
  assign p00_abcd_and = ab0 & cd0;
  assign p01_abcd_and = ab0 & cd1;
  assign p10_abcd_and = ab1 & cd0;
  assign p11_abcd_and = ab1 & cd1;
  assign _04_ = p00_abcd_and ^ p01_abcd_and;
  assign and_ab_cd_0 = _04_ ^ r2;
  assign _05_ = p11_abcd_and ^ p10_abcd_and;
  assign and_ab_cd_1 = _05_ ^ r2;
  assign _06_ = ab0 ^ cd0;
  assign abcd0 = _06_ ^ and_ab_cd_0;
  assign _07_ = ab1 ^ cd1;
  assign abcd1 = _07_ ^ and_ab_cd_1;
  assign p00_ab = a0 & b0;
  assign p01_ab = a0 & b1;
  assign p10_ab = a1 & b0;
  assign p11_ab = a1 & b1;
  assign _00_ = p00_ab ^ p01_ab;
  assign ab0 = _00_ ^ r0;
  assign _01_ = p11_ab ^ p10_ab;
  assign ab1 = _01_ ^ r0;
  assign p00_cd = c0 & d0;
  assign p01_cd = c0 & d1;
  assign p10_cd = c1 & d0;
  assign p11_cd = c1 & d1;
  assign _02_ = p00_cd ^ p01_cd;
  assign cd0 = _02_ ^ r1;
  assign _03_ = p11_cd ^ p10_cd;
  assign cd1 = _03_ ^ r1;
  assign out0 = abcd0;
  assign out1 = abcd1;
endmodule
