/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module circuit(clk, too_cold0, too_cold1, too_hot0, too_hot1, mode0, mode1, fan_on0, fan_on1, r0, r1, r2, r3, heater0, heater1, aircon0, aircon1, fan0, fan1);
  output aircon0;
  wire aircon0_w;
  output aircon1;
  wire aircon1_w;
  input clk;
  output fan0;
  wire fan0_w;
  output fan1;
  wire fan1_w;
  input fan_on0;
  input fan_on1;
  output heater0;
  wire heater0_w;
  output heater1;
  wire heater1_w;
  input mode0;
  input mode1;
  input r0;
  input r1;
  input r2;
  input r3;
  input too_cold0;
  input too_cold1;
  input too_hot0;
  input too_hot1;
  DFF _0_ (
    .C(clk),
    .D(heater1_w),
    .Q(heater1)
  );
  DFF _1_ (
    .C(clk),
    .D(aircon0_w),
    .Q(aircon0)
  );
  DFF _2_ (
    .C(clk),
    .D(aircon1_w),
    .Q(aircon1)
  );
  DFF _3_ (
    .C(clk),
    .D(fan1_w),
    .Q(fan1)
  );
  DFF _4_ (
    .C(clk),
    .D(heater0_w),
    .Q(heater0)
  );
  DFF _5_ (
    .C(clk),
    .D(fan0_w),
    .Q(fan0)
  );
  top_module_masked dut (
    .aircon0(aircon0_w),
    .aircon1(aircon1_w),
    .fan0(fan0_w),
    .fan1(fan1_w),
    .fan_on0(fan_on0),
    .fan_on1(fan_on1),
    .heater0(heater0_w),
    .heater1(heater1_w),
    .mode0(mode0),
    .mode1(mode1),
    .r0(r0),
    .r1(r1),
    .r2(r2),
    .r3(r3),
    .too_cold0(too_cold0),
    .too_cold1(too_cold1),
    .too_hot0(too_hot0),
    .too_hot1(too_hot1)
  );
endmodule

module top_module_masked(too_cold0, too_cold1, too_hot0, too_hot1, mode0, mode1, fan_on0, fan_on1, r0, r1, r2, r3, heater0, heater1, aircon0, aircon1, fan0, fan1);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  output aircon0;
  output aircon1;
  wire and3_c0;
  wire and3_c1;
  wire and4_c0;
  wire and4_c1;
  output fan0;
  output fan1;
  input fan_on0;
  input fan_on1;
  wire fo_0;
  wire fo_1;
  output heater0;
  output heater1;
  input mode0;
  input mode1;
  wire not_mode0;
  wire not_mode1;
  wire p1_00;
  wire p1_01;
  wire p1_10;
  wire p1_11;
  wire p2_00;
  wire p2_01;
  wire p2_10;
  wire p2_11;
  wire p3_00;
  wire p3_01;
  wire p3_10;
  wire p3_11;
  wire p4_00;
  wire p4_01;
  wire p4_10;
  wire p4_11;
  input r0;
  input r1;
  input r2;
  input r3;
  input too_cold0;
  input too_cold1;
  input too_hot0;
  input too_hot1;
  wire w1_0;
  wire w1_1;
  wire w2_0;
  wire w2_1;
  assign not_mode0 = ~mode0;
  assign not_mode1 = ~mode1;
  assign p1_00 = mode0 & too_cold0;
  assign p1_01 = mode0 & too_cold1;
  assign p1_10 = mode1 & too_cold0;
  assign p1_11 = mode1 & too_cold1;
  assign _00_ = p1_00 ^ p1_01;
  assign w1_0 = _00_ ^ r0;
  assign _01_ = p1_11 ^ p1_10;
  assign w1_1 = _01_ ^ r0;
  assign p2_00 = not_mode0 & too_hot0;
  assign p2_01 = not_mode0 & too_hot1;
  assign p2_10 = not_mode1 & too_hot0;
  assign p2_11 = not_mode1 & too_hot1;
  assign _02_ = p2_00 ^ p2_01;
  assign w2_0 = _02_ ^ r1;
  assign _03_ = p2_11 ^ p2_10;
  assign w2_1 = _03_ ^ r1;
  assign p3_00 = fan_on0 & w1_0;
  assign p3_01 = fan_on0 & w1_1;
  assign p3_10 = fan_on1 & w1_0;
  assign p3_11 = fan_on1 & w1_1;
  assign _04_ = p3_00 ^ p3_01;
  assign and3_c0 = _04_ ^ r2;
  assign _05_ = p3_11 ^ p3_10;
  assign and3_c1 = _05_ ^ r2;
  assign _06_ = fan_on0 ^ w1_0;
  assign fo_0 = _06_ ^ and3_c0;
  assign _07_ = fan_on1 ^ w1_1;
  assign fo_1 = _07_ ^ and3_c1;
  assign p4_00 = fo_0 & w2_0;
  assign p4_01 = fo_0 & w2_1;
  assign p4_10 = fo_1 & w2_0;
  assign p4_11 = fo_1 & w2_1;
  assign _08_ = p4_00 ^ p4_01;
  assign and4_c0 = _08_ ^ r3;
  assign _09_ = p4_11 ^ p4_10;
  assign and4_c1 = _09_ ^ r3;
  assign _10_ = fo_0 ^ w2_0;
  assign fan0 = _10_ ^ and4_c0;
  assign _11_ = fo_1 ^ w2_1;
  assign fan1 = _11_ ^ and4_c1;
  assign aircon0 = w2_0;
  assign aircon1 = w2_1;
  assign heater0 = w1_0;
  assign heater1 = w1_1;
endmodule
