/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module circuit(clk, A0, A1, B0, B1, rN, Sum0, Sum1, Cout0, Cout1);
  input A0;
  input A1;
  input B0;
  input B1;
  output Cout0;
  output Cout1;
  output Sum0;
  output Sum1;
  input clk;
  input rN;
  halfAdder_Behavorial_masked dut (
    .A0(A0),
    .A1(A1),
    .B0(B0),
    .B1(B1),
    .Cout0(Cout0),
    .Cout1(Cout1),
    .Sum0(Sum0),
    .Sum1(Sum1),
    .rN(rN)
  );
endmodule

module halfAdder_Behavorial_masked(A0, A1, B0, B1, rN, Sum0, Sum1, Cout0, Cout1);
  wire _00_;
  wire _01_;
  input A0;
  input A1;
  input B0;
  input B1;
  output Cout0;
  output Cout1;
  output Sum0;
  output Sum1;
  wire p00;
  wire p01;
  wire p10;
  wire p11;
  input rN;
  assign Sum0 = A0 ^ B0;
  assign Sum1 = A1 ^ B1;
  assign p00 = A0 & B0;
  assign p01 = A0 & B1;
  assign p10 = A1 & B0;
  assign p11 = A1 & B1;
  assign _00_ = p00 ^ p01;
  assign Cout0 = _00_ ^ rN;
  assign _01_ = p11 ^ p10;
  assign Cout1 = _01_ ^ rN;
endmodule
