/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module circuit(clk, a0, a1, b0, b1, r0, r1, r2, y0, y1);
  input a0;
  input a1;
  input b0;
  input b1;
  input clk;
  input r0;
  input r1;
  input r2;
  output y0;
  wire y0_w;
  output y1;
  wire y1_w;
  DFF _0_ (
    .C(clk),
    .D(y1_w),
    .Q(y1)
  );
  DFF _1_ (
    .C(clk),
    .D(y0_w),
    .Q(y0)
  );
  xor_pass_gate_masked uut (
    .a0(a0),
    .a1(a1),
    .b0(b0),
    .b1(b1),
    .r0(r0),
    .r1(r1),
    .r2(r2),
    .y0(y0_w),
    .y1(y1_w)
  );
endmodule

module xor_pass_gate_masked(a0, a1, b0, b1, r0, r1, r2, y0, y1);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  input a0;
  input a1;
  wire a_and_not_b0;
  wire a_and_not_b1;
  input b0;
  input b1;
  wire not_a0;
  wire not_a1;
  wire not_a_and_b0;
  wire not_a_and_b1;
  wire not_b0;
  wire not_b1;
  wire p00_0;
  wire p00_1;
  wire p00_2;
  wire p01_0;
  wire p01_1;
  wire p01_2;
  wire p10_0;
  wire p10_1;
  wire p10_2;
  wire p11_0;
  wire p11_1;
  wire p11_2;
  input r0;
  input r1;
  input r2;
  wire t0;
  wire t1;
  output y0;
  output y1;
  assign not_b0 = ~b0;
  assign not_b1 = ~b1;
  assign not_a0 = ~a0;
  assign not_a1 = ~a1;
  assign _03_ = p11_1 ^ p10_1;
  assign not_a_and_b1 = _03_ ^ r1;
  assign p00_2 = a_and_not_b0 & not_a_and_b0;
  assign p01_2 = a_and_not_b0 & not_a_and_b1;
  assign p10_2 = a_and_not_b1 & not_a_and_b0;
  assign p11_2 = a_and_not_b1 & not_a_and_b1;
  assign _04_ = p00_2 ^ p01_2;
  assign t0 = _04_ ^ r2;
  assign _05_ = p11_2 ^ p10_2;
  assign t1 = _05_ ^ r2;
  assign _06_ = a_and_not_b0 ^ not_a_and_b0;
  assign y0 = _06_ ^ t0;
  assign _07_ = a_and_not_b1 ^ not_a_and_b1;
  assign y1 = _07_ ^ t1;
  assign p00_0 = a0 & not_b0;
  assign p01_0 = a0 & not_b1;
  assign p10_0 = a1 & not_b0;
  assign p11_0 = a1 & not_b1;
  assign _00_ = p00_0 ^ p01_0;
  assign a_and_not_b0 = _00_ ^ r0;
  assign _01_ = p11_0 ^ p10_0;
  assign a_and_not_b1 = _01_ ^ r0;
  assign p00_1 = not_a0 & b0;
  assign p01_1 = not_a0 & b1;
  assign p10_1 = not_a1 & b0;
  assign p11_1 = not_a1 & b1;
  assign _02_ = p00_1 ^ p01_1;
  assign not_a_and_b0 = _02_ ^ r1;
endmodule
