/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module circuit(clk, i_A0, i_A1, i_B0, i_B1, r0, o_S0, o_S1, o_C0, o_C1);
  wire C0_w;
  wire C1_w;
  wire S0_w;
  wire S1_w;
  input clk;
  input i_A0;
  input i_A1;
  input i_B0;
  input i_B1;
  output o_C0;
  output o_C1;
  output o_S0;
  output o_S1;
  input r0;
  DFF _0_ (
    .C(clk),
    .D(S1_w),
    .Q(o_S1)
  );
  DFF _1_ (
    .C(clk),
    .D(C0_w),
    .Q(o_C0)
  );
  DFF _2_ (
    .C(clk),
    .D(C1_w),
    .Q(o_C1)
  );
  DFF _3_ (
    .C(clk),
    .D(S0_w),
    .Q(o_S0)
  );
  half_adder_masked dut (
    .A0(i_A0),
    .A1(i_A1),
    .B0(i_B0),
    .B1(i_B1),
    .C0(C0_w),
    .C1(C1_w),
    .S0(S0_w),
    .S1(S1_w),
    .r0(r0)
  );
endmodule

module half_adder_masked(A0, A1, B0, B1, r0, S0, S1, C0, C1);
  wire _00_;
  wire _01_;
  input A0;
  input A1;
  input B0;
  input B1;
  output C0;
  output C1;
  output S0;
  output S1;
  wire p00;
  wire p01;
  wire p10;
  wire p11;
  input r0;
  assign S0 = A0 ^ B0;
  assign S1 = A1 ^ B1;
  assign p00 = A0 & B0;
  assign p01 = A0 & B1;
  assign p10 = A1 & B0;
  assign p11 = A1 & B1;
  assign _00_ = p00 ^ p01;
  assign C0 = _00_ ^ r0;
  assign _01_ = p11 ^ p10;
  assign C1 = _01_ ^ r0;
endmodule
