/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module circuit(clk, a, b, r, y);
  input [1:0] a;
  input [1:0] b;
  input clk;
  input [1:0] r;
  output [1:0] y;
  masked_and u_masked_and (
    .a0(a[0]),
    .a1(a[1]),
    .b0(b[0]),
    .b1(b[1]),
    .clk(clk),
    .r0(r[0]),
    .r1(r[1]),
    .y0(y[0]),
    .y1(y[1])
  );
endmodule

module masked_and(clk, a0, a1, b0, b1, r0, r1, y0, y1);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  input a0;
  input a1;
  input b0;
  input b1;
  input clk;
  wire p00;
  wire p01;
  wire p10;
  wire p11;
  input r0;
  input r1;
  wire s0;
  wire s1;
  output y0;
  output y1;
  DFF _08_ (
    .C(clk),
    .D(_02_),
    .Q(p10)
  );
  DFF _09_ (
    .C(clk),
    .D(_03_),
    .Q(p11)
  );
  DFF _10_ (
    .C(clk),
    .D(_00_),
    .Q(p00)
  );
  DFF _11_ (
    .C(clk),
    .D(s1),
    .Q(y1)
  );
  DFF _12_ (
    .C(clk),
    .D(_04_),
    .Q(s0)
  );
  DFF _13_ (
    .C(clk),
    .D(_05_),
    .Q(s1)
  );
  DFF _14_ (
    .C(clk),
    .D(_01_),
    .Q(p01)
  );
  DFF _15_ (
    .C(clk),
    .D(s0),
    .Q(y0)
  );
  assign _03_ = a1 & b1;
  assign _00_ = a0 & b0;
  assign _01_ = a0 & b1;
  assign _02_ = a1 & b0;
  assign _05_ = _07_ ^ r1;
  assign _04_ = p00 ^ r0;
  assign _06_ = p01 ^ p10;
  assign _07_ = _06_ ^ p11;
endmodule
