/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module circuit(clk, i_a0, i_a1, i_b0, i_b1, r0, o_p0, o_p1, o_g0, o_g1);
  input clk;
  input i_a0;
  input i_a1;
  input i_b0;
  input i_b1;
  output o_g0;
  output o_g1;
  output o_p0;
  output o_p1;
  input r0;
  pg_masked uut (
    .clk(clk),
    .i_a0(i_a0),
    .i_a1(i_a1),
    .i_b0(i_b0),
    .i_b1(i_b1),
    .o_g0(o_g0),
    .o_g1(o_g1),
    .o_p0(o_p0),
    .o_p1(o_p1),
    .r0(r0)
  );
endmodule

module pg_masked(clk, i_a0, i_a1, i_b0, i_b1, r0, o_p0, o_p1, o_g0, o_g1);
  wire _00_;
  wire _01_;
  input clk;
  wire g0;
  wire g1;
  input i_a0;
  input i_a1;
  input i_b0;
  input i_b1;
  output o_g0;
  output o_g1;
  output o_p0;
  output o_p1;
  wire p0;
  wire p1;
  input r0;
  wire u00;
  wire u01;
  wire u10;
  wire u11;
  DFF _02_ (
    .C(clk),
    .D(p1),
    .Q(o_p1)
  );
  DFF _03_ (
    .C(clk),
    .D(g0),
    .Q(o_g0)
  );
  DFF _04_ (
    .C(clk),
    .D(g1),
    .Q(o_g1)
  );
  DFF _05_ (
    .C(clk),
    .D(p0),
    .Q(o_p0)
  );
  assign p0 = i_a0 ^ i_b0;
  assign p1 = i_a1 ^ i_b1;
  assign u00 = i_a0 & i_b0;
  assign u01 = i_a0 & i_b1;
  assign u10 = i_a1 & i_b0;
  assign u11 = i_a1 & i_b1;
  assign _00_ = u00 ^ u01;
  assign g0 = _00_ ^ r0;
  assign _01_ = u11 ^ u10;
  assign g1 = _01_ ^ r0;
endmodule
