/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module and_gate_masked(A0, A1, B0, B1, rN, Y0, Y1);
  wire _0_;
  wire _1_;
  input A0;
  input A1;
  input B0;
  input B1;
  output Y0;
  output Y1;
  wire p00;
  wire p01;
  wire p10;
  wire p11;
  input rN;
  assign p00 = A0 & B0;
  assign p01 = A0 & B1;
  assign p10 = A1 & B0;
  assign p11 = A1 & B1;
  assign _0_ = p00 ^ p01;
  assign Y0 = _0_ ^ rN;
  assign _1_ = p11 ^ p10;
  assign Y1 = _1_ ^ rN;
endmodule

module circuit(clk, i_A0, i_A1, i_B0, i_B1, rN, o_Y0, o_Y1);
  wire Y0_w;
  wire Y1_w;
  input clk;
  input i_A0;
  input i_A1;
  input i_B0;
  input i_B1;
  output o_Y0;
  output o_Y1;
  input rN;
  DFF _0_ (
    .C(clk),
    .D(Y1_w),
    .Q(o_Y1)
  );
  DFF _1_ (
    .C(clk),
    .D(Y0_w),
    .Q(o_Y0)
  );
  and_gate_masked dut (
    .A0(i_A0),
    .A1(i_A1),
    .B0(i_B0),
    .B1(i_B1),
    .Y0(Y0_w),
    .Y1(Y1_w),
    .rN(rN)
  );
endmodule
