/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module circuit(clk, i_a0, i_a1, i_b0, i_b1, r0, o_p0, o_p1, o_g0, o_g1);
  input clk;
  input i_a0;
  input i_a1;
  input i_b0;
  input i_b1;
  output o_g0;
  output o_g1;
  output o_p0;
  output o_p1;
  input r0;
  pg_masked uut (
    .i_a0(i_a0),
    .i_a1(i_a1),
    .i_b0(i_b0),
    .i_b1(i_b1),
    .o_g0(o_g0),
    .o_g1(o_g1),
    .o_p0(o_p0),
    .o_p1(o_p1),
    .r0(r0)
  );
endmodule

module pg_masked(i_a0, i_a1, i_b0, i_b1, r0, o_p0, o_p1, o_g0, o_g1);
  wire _00_;
  wire _01_;
  input i_a0;
  input i_a1;
  input i_b0;
  input i_b1;
  output o_g0;
  output o_g1;
  output o_p0;
  output o_p1;
  input r0;
  wire t00;
  wire t01;
  wire t10;
  wire t11;
  assign o_p0 = i_a0 ^ i_b0;
  assign o_p1 = i_a1 ^ i_b1;
  assign t00 = i_a0 & i_b0;
  assign t01 = i_a0 & i_b1;
  assign t10 = i_a1 & i_b0;
  assign t11 = i_a1 & i_b1;
  assign _00_ = t00 ^ t01;
  assign _01_ = _00_ ^ t10;
  assign o_g0 = _01_ ^ r0;
  assign o_g1 = t11 ^ r0;
endmodule
