/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module circuit(clk, A0, A1, B0, B1, r0, r1, r2, Y0, Y1);
  input A0;
  input A1;
  input B0;
  input B1;
  output Y0;
  wire Y0_w;
  output Y1;
  wire Y1_w;
  input clk;
  input r0;
  input r1;
  input r2;
  DFF _0_ (
    .C(clk),
    .D(Y1_w),
    .Q(Y1)
  );
  DFF _1_ (
    .C(clk),
    .D(Y0_w),
    .Q(Y0)
  );
  xor_gate_masked uut (
    .A0(A0),
    .A1(A1),
    .B0(B0),
    .B1(B1),
    .Y0(Y0_w),
    .Y1(Y1_w),
    .r0(r0),
    .r1(r1),
    .r2(r2)
  );
endmodule

module xor_gate_masked(A0, A1, B0, B1, r0, r1, r2, Y0, Y1);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  input A0;
  input A1;
  input B0;
  input B1;
  output Y0;
  output Y1;
  wire and12_0;
  wire and12_1;
  wire not_A0;
  wire not_A1;
  wire not_B0;
  wire not_B1;
  wire p1_00;
  wire p1_01;
  wire p1_10;
  wire p1_11;
  wire p2_00;
  wire p2_01;
  wire p2_10;
  wire p2_11;
  wire p3_00;
  wire p3_01;
  wire p3_10;
  wire p3_11;
  wire path1_0;
  wire path1_1;
  wire path2_0;
  wire path2_1;
  input r0;
  input r1;
  input r2;
  assign not_A0 = ~A0;
  assign not_A1 = ~A1;
  assign not_B0 = ~B0;
  assign not_B1 = ~B1;
  assign _03_ = p2_11 ^ p2_10;
  assign path2_1 = _03_ ^ r1;
  assign p3_00 = path1_0 & path2_0;
  assign p3_01 = path1_0 & path2_1;
  assign p3_10 = path1_1 & path2_0;
  assign p3_11 = path1_1 & path2_1;
  assign _04_ = p3_00 ^ p3_01;
  assign and12_0 = _04_ ^ r2;
  assign _05_ = p3_11 ^ p3_10;
  assign and12_1 = _05_ ^ r2;
  assign _06_ = path1_0 ^ path2_0;
  assign Y0 = _06_ ^ and12_0;
  assign _07_ = path1_1 ^ path2_1;
  assign Y1 = _07_ ^ and12_1;
  assign p1_00 = not_A0 & B0;
  assign p1_01 = not_A0 & B1;
  assign p1_10 = not_A1 & B0;
  assign p1_11 = not_A1 & B1;
  assign _00_ = p1_00 ^ p1_01;
  assign path1_0 = _00_ ^ r0;
  assign _01_ = p1_11 ^ p1_10;
  assign path1_1 = _01_ ^ r0;
  assign p2_00 = A0 & not_B0;
  assign p2_01 = A0 & not_B1;
  assign p2_10 = A1 & not_B0;
  assign p2_11 = A1 & not_B1;
  assign _02_ = p2_00 ^ p2_01;
  assign path2_0 = _02_ ^ r1;
endmodule
