/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module circuit(clk, i_A0, i_A1, i_B0, i_B1, rN, o_SUM0, o_SUM1, o_CARRY0, o_CARRY1);
  wire CARRY0_w;
  wire CARRY1_w;
  wire SUM0_w;
  wire SUM1_w;
  input clk;
  input i_A0;
  input i_A1;
  input i_B0;
  input i_B1;
  output o_CARRY0;
  output o_CARRY1;
  output o_SUM0;
  output o_SUM1;
  input rN;
  DFF _0_ (
    .C(clk),
    .D(SUM1_w),
    .Q(o_SUM1)
  );
  DFF _1_ (
    .C(clk),
    .D(CARRY0_w),
    .Q(o_CARRY0)
  );
  DFF _2_ (
    .C(clk),
    .D(CARRY1_w),
    .Q(o_CARRY1)
  );
  DFF _3_ (
    .C(clk),
    .D(SUM0_w),
    .Q(o_SUM0)
  );
  half_adder_masked dut (
    .A0(i_A0),
    .A1(i_A1),
    .B0(i_B0),
    .B1(i_B1),
    .CARRY0(CARRY0_w),
    .CARRY1(CARRY1_w),
    .SUM0(SUM0_w),
    .SUM1(SUM1_w),
    .rN(rN)
  );
endmodule

module half_adder_masked(A0, A1, B0, B1, rN, SUM0, SUM1, CARRY0, CARRY1);
  wire _00_;
  wire _01_;
  input A0;
  input A1;
  input B0;
  input B1;
  output CARRY0;
  output CARRY1;
  output SUM0;
  output SUM1;
  wire p00;
  wire p01;
  wire p10;
  wire p11;
  input rN;
  assign SUM0 = A0 ^ B0;
  assign SUM1 = A1 ^ B1;
  assign p00 = A0 & B0;
  assign p01 = A0 & B1;
  assign p10 = A1 & B0;
  assign p11 = A1 & B1;
  assign _00_ = p00 ^ p01;
  assign CARRY0 = _00_ ^ rN;
  assign _01_ = p11 ^ p10;
  assign CARRY1 = _01_ ^ rN;
endmodule
