/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module AND_gate_masked(a0, a1, b0, b1, rN, out0, out1);
  wire _0_;
  wire _1_;
  input a0;
  input a1;
  input b0;
  input b1;
  output out0;
  output out1;
  wire p00;
  wire p01;
  wire p10;
  wire p11;
  input rN;
  assign p00 = a0 & b0;
  assign p01 = a0 & b1;
  assign p10 = a1 & b0;
  assign p11 = a1 & b1;
  assign _0_ = p00 ^ p01;
  assign out0 = _0_ ^ rN;
  assign _1_ = p11 ^ p10;
  assign out1 = _1_ ^ rN;
endmodule

module circuit(clk, i_a0, i_a1, i_b0, i_b1, rN, o_out0, o_out1);
  input clk;
  input i_a0;
  input i_a1;
  input i_b0;
  input i_b1;
  output o_out0;
  output o_out1;
  wire out0_w;
  wire out1_w;
  input rN;
  DFF _0_ (
    .C(clk),
    .D(out1_w),
    .Q(o_out1)
  );
  DFF _1_ (
    .C(clk),
    .D(out0_w),
    .Q(o_out0)
  );
  AND_gate_masked dut (
    .a0(i_a0),
    .a1(i_a1),
    .b0(i_b0),
    .b1(i_b1),
    .out0(out0_w),
    .out1(out1_w),
    .rN(rN)
  );
endmodule
