/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module circuit(clk, i_A0, i_A1, i_B0, i_B1, rN, o_S0, o_S1, o_Cout0, o_Cout1);
  wire Cout0_w;
  wire Cout1_w;
  wire S0_w;
  wire S1_w;
  input clk;
  input i_A0;
  input i_A1;
  input i_B0;
  input i_B1;
  output o_Cout0;
  output o_Cout1;
  output o_S0;
  output o_S1;
  input rN;
  DFF _0_ (
    .C(clk),
    .D(S1_w),
    .Q(o_S1)
  );
  DFF _1_ (
    .C(clk),
    .D(Cout0_w),
    .Q(o_Cout0)
  );
  DFF _2_ (
    .C(clk),
    .D(Cout1_w),
    .Q(o_Cout1)
  );
  DFF _3_ (
    .C(clk),
    .D(S0_w),
    .Q(o_S0)
  );
  half_adder_masked dut (
    .A0(i_A0),
    .A1(i_A1),
    .B0(i_B0),
    .B1(i_B1),
    .Cout0(Cout0_w),
    .Cout1(Cout1_w),
    .S0(S0_w),
    .S1(S1_w),
    .rN(rN)
  );
endmodule

module half_adder_masked(A0, A1, B0, B1, rN, S0, S1, Cout0, Cout1);
  wire _00_;
  wire _01_;
  input A0;
  input A1;
  input B0;
  input B1;
  output Cout0;
  output Cout1;
  output S0;
  output S1;
  wire p00;
  wire p01;
  wire p10;
  wire p11;
  input rN;
  assign S0 = A0 ^ B0;
  assign S1 = A1 ^ B1;
  assign p00 = A0 & B0;
  assign p01 = A0 & B1;
  assign p10 = A1 & B0;
  assign p11 = A1 & B1;
  assign _00_ = p00 ^ p01;
  assign Cout0 = _00_ ^ rN;
  assign _01_ = p11 ^ p10;
  assign Cout1 = _01_ ^ rN;
endmodule
