/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module circuit(clk, rst, a0, a1, b0, b1, r0, p0, p1, g0, g1);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  input a0;
  wire a0_r;
  input a1;
  wire a1_r;
  input b0;
  wire b0_r;
  input b1;
  wire b1_r;
  input clk;
  output g0;
  wire g0_w;
  output g1;
  wire g1_w;
  output p0;
  wire p0_w;
  output p1;
  wire p1_w;
  input r0;
  wire r0_r;
  input rst;
  assign _07_ = rst ? 1'h0 : p1_w;
  assign _08_ = rst ? 1'h0 : r0;
  assign _03_ = rst ? 1'h0 : b1;
  assign _02_ = rst ? 1'h0 : b0;
  assign _05_ = rst ? 1'h0 : g1_w;
  assign _01_ = rst ? 1'h0 : a1;
  assign _00_ = rst ? 1'h0 : a0;
  assign _06_ = rst ? 1'h0 : p0_w;
  assign _04_ = rst ? 1'h0 : g0_w;
  DFF _18_ (
    .C(clk),
    .D(_06_),
    .Q(p0)
  );
  DFF _19_ (
    .C(clk),
    .D(_07_),
    .Q(p1)
  );
  DFF _20_ (
    .C(clk),
    .D(_04_),
    .Q(g0)
  );
  DFF _21_ (
    .C(clk),
    .D(_05_),
    .Q(g1)
  );
  DFF _22_ (
    .C(clk),
    .D(_00_),
    .Q(a0_r)
  );
  DFF _23_ (
    .C(clk),
    .D(_01_),
    .Q(a1_r)
  );
  DFF _24_ (
    .C(clk),
    .D(_02_),
    .Q(b0_r)
  );
  DFF _25_ (
    .C(clk),
    .D(_03_),
    .Q(b1_r)
  );
  DFF _26_ (
    .C(clk),
    .D(_08_),
    .Q(r0_r)
  );
  pg_masked dut (
    .i_a0(a0_r),
    .i_a1(a1_r),
    .i_b0(b0_r),
    .i_b1(b1_r),
    .o_g0(g0_w),
    .o_g1(g1_w),
    .o_p0(p0_w),
    .o_p1(p1_w),
    .rN(r0_r)
  );
endmodule

module pg_masked(i_a0, i_a1, i_b0, i_b1, rN, o_p0, o_p1, o_g0, o_g1);
  wire _00_;
  wire _01_;
  wire g0_temp0;
  wire g0_temp1;
  wire g1_temp0;
  wire g1_temp1;
  input i_a0;
  input i_a1;
  input i_b0;
  input i_b1;
  output o_g0;
  output o_g1;
  output o_p0;
  output o_p1;
  input rN;
  assign o_p0 = i_a0 ^ i_b0;
  assign o_p1 = i_a1 ^ i_b1;
  assign g0_temp0 = i_a0 & i_b0;
  assign g0_temp1 = i_a0 & i_b1;
  assign g1_temp0 = i_a1 & i_b0;
  assign g1_temp1 = i_a1 & i_b1;
  assign _00_ = g0_temp0 ^ g0_temp1;
  assign o_g0 = _00_ ^ rN;
  assign _01_ = g1_temp1 ^ g1_temp0;
  assign o_g1 = _01_ ^ rN;
endmodule
