/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module circuit(clk, a0, a1, b0, b1, r0, r1, r2, y0, y1);
  input a0;
  input a1;
  input b0;
  input b1;
  input clk;
  input r0;
  input r1;
  input r2;
  output y0;
  wire y0_w;
  output y1;
  wire y1_w;
  DFF _0_ (
    .C(clk),
    .D(y1_w),
    .Q(y1)
  );
  DFF _1_ (
    .C(clk),
    .D(y0_w),
    .Q(y0)
  );
  xor_gate_pass_masked uut (
    .a0(a0),
    .a1(a1),
    .b0(b0),
    .b1(b1),
    .r0(r0),
    .r1(r1),
    .r2(r2),
    .y0(y0_w),
    .y1(y1_w)
  );
endmodule

module xor_gate_pass_masked(a0, a1, b0, b1, r0, r1, r2, y0, y1);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  input a0;
  input a1;
  input b0;
  input b1;
  wire na0;
  wire na1;
  wire nb0;
  wire nb1;
  wire p1_0;
  wire p1_1;
  wire p1_p00;
  wire p1_p01;
  wire p1_p10;
  wire p1_p11;
  wire p2_0;
  wire p2_1;
  wire p2_p00;
  wire p2_p01;
  wire p2_p10;
  wire p2_p11;
  input r0;
  input r1;
  input r2;
  wire t0;
  wire t1;
  wire t_p00;
  wire t_p01;
  wire t_p10;
  wire t_p11;
  output y0;
  output y1;
  assign nb0 = ~b0;
  assign nb1 = ~b1;
  assign na0 = ~a0;
  assign na1 = ~a1;
  assign _03_ = p2_p11 ^ p2_p10;
  assign p2_1 = _03_ ^ r1;
  assign t_p00 = p1_0 & p2_0;
  assign t_p01 = p1_0 & p2_1;
  assign t_p10 = p1_1 & p2_0;
  assign t_p11 = p1_1 & p2_1;
  assign _04_ = t_p00 ^ t_p01;
  assign t0 = _04_ ^ r2;
  assign _05_ = t_p11 ^ t_p10;
  assign t1 = _05_ ^ r2;
  assign _06_ = p1_0 ^ p2_0;
  assign y0 = _06_ ^ t0;
  assign _07_ = p1_1 ^ p2_1;
  assign y1 = _07_ ^ t1;
  assign p1_p00 = a0 & nb0;
  assign p1_p01 = a0 & nb1;
  assign p1_p10 = a1 & nb0;
  assign p1_p11 = a1 & nb1;
  assign _00_ = p1_p00 ^ p1_p01;
  assign p1_0 = _00_ ^ r0;
  assign _01_ = p1_p11 ^ p1_p10;
  assign p1_1 = _01_ ^ r0;
  assign p2_p00 = na0 & b0;
  assign p2_p01 = na0 & b1;
  assign p2_p10 = na1 & b0;
  assign p2_p11 = na1 & b1;
  assign _02_ = p2_p00 ^ p2_p01;
  assign p2_0 = _02_ ^ r1;
endmodule
