/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module circuit(clk, i_A0, i_A1, i_B0, i_B1, r0, o_Sum0, o_Sum1, o_Carry0, o_Carry1);
  wire Carry0_w;
  wire Carry1_w;
  wire Sum0_w;
  wire Sum1_w;
  input clk;
  input i_A0;
  input i_A1;
  input i_B0;
  input i_B1;
  output o_Carry0;
  output o_Carry1;
  output o_Sum0;
  output o_Sum1;
  input r0;
  DFF _0_ (
    .C(clk),
    .D(Sum1_w),
    .Q(o_Sum1)
  );
  DFF _1_ (
    .C(clk),
    .D(Carry0_w),
    .Q(o_Carry0)
  );
  DFF _2_ (
    .C(clk),
    .D(Carry1_w),
    .Q(o_Carry1)
  );
  DFF _3_ (
    .C(clk),
    .D(Sum0_w),
    .Q(o_Sum0)
  );
  half_adder_masked dut (
    .A0(i_A0),
    .A1(i_A1),
    .B0(i_B0),
    .B1(i_B1),
    .Carry0(Carry0_w),
    .Carry1(Carry1_w),
    .Sum0(Sum0_w),
    .Sum1(Sum1_w),
    .r0(r0)
  );
endmodule

module half_adder_masked(A0, A1, B0, B1, r0, Sum0, Sum1, Carry0, Carry1);
  wire _00_;
  wire _01_;
  input A0;
  input A1;
  input B0;
  input B1;
  output Carry0;
  output Carry1;
  output Sum0;
  output Sum1;
  wire Sum_temp0;
  wire Sum_temp1;
  wire p00;
  wire p01;
  wire p10;
  wire p11;
  input r0;
  assign Sum0 = A0 ^ B0;
  assign Sum1 = A1 ^ B1;
  assign p00 = A0 & B0;
  assign p01 = A0 & B1;
  assign p10 = A1 & B0;
  assign p11 = A1 & B1;
  assign _00_ = p00 ^ p01;
  assign Carry0 = _00_ ^ r0;
  assign _01_ = p11 ^ p10;
  assign Carry1 = _01_ ^ r0;
  assign Sum_temp0 = Sum0;
  assign Sum_temp1 = Sum1;
endmodule
