/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module EXP_GATE_3_masked(A0, A1, B0, B1, C0, C1, D0, D1, E0, E1, F0, F1, G0, G1, H0, H1, I0, I1, J0, J1, r0, r1, r2, r3, r4, r5, r6, r7, r8, X0, X1, XBAR0, XBAR1);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  input A0;
  input A1;
  input B0;
  input B1;
  input C0;
  input C1;
  input D0;
  input D1;
  input E0;
  input E1;
  input F0;
  input F1;
  input G0;
  input G1;
  input H0;
  input H1;
  input I0;
  input I1;
  input J0;
  input J1;
  output X0;
  output X1;
  output XBAR0;
  output XBAR1;
  wire X_w0;
  wire X_w1;
  wire a_p00;
  wire a_p01;
  wire a_p10;
  wire a_p11;
  wire a_w0;
  wire a_w1;
  wire and_ab0;
  wire and_ab1;
  wire and_ab_p00;
  wire and_ab_p01;
  wire and_ab_p10;
  wire and_ab_p11;
  wire and_or1c0;
  wire and_or1c1;
  wire and_or1c_p00;
  wire and_or1c_p01;
  wire and_or1c_p10;
  wire and_or1c_p11;
  wire and_or2d0;
  wire and_or2d1;
  wire and_or2d_p00;
  wire and_or2d_p01;
  wire and_or2d_p10;
  wire and_or2d_p11;
  wire b_p00;
  wire b_p01;
  wire b_p10;
  wire b_p11;
  wire b_w0;
  wire b_w1;
  wire c_p00;
  wire c_p01;
  wire c_p10;
  wire c_p11;
  wire c_w0;
  wire c_w1;
  wire d_p00;
  wire d_p01;
  wire d_p10;
  wire d_p11;
  wire d_w0;
  wire d_w1;
  wire or1_0;
  wire or1_1;
  wire or2_0;
  wire or2_1;
  input r0;
  input r1;
  input r2;
  input r3;
  input r4;
  input r5;
  input r6;
  input r7;
  input r8;
  wire t_cd0;
  wire t_cd1;
  wire t_cd_p00;
  wire t_cd_p01;
  wire t_cd_p10;
  wire t_cd_p11;
  wire t_fg0;
  wire t_fg1;
  wire t_fg_p00;
  wire t_fg_p01;
  wire t_fg_p10;
  wire t_fg_p11;
  assign XBAR0 = ~X_w0;
  assign a_p00 = A0 & B0;
  assign a_p01 = A0 & B1;
  assign a_p10 = A1 & B0;
  assign a_p11 = A1 & B1;
  assign _004_ = a_p00 ^ a_p01;
  assign a_w0 = _004_ ^ r0;
  assign _005_ = a_p11 ^ a_p10;
  assign a_w1 = _005_ ^ r0;
  assign t_cd_p00 = C0 & D0;
  assign t_cd_p01 = C0 & D1;
  assign t_cd_p10 = C1 & D0;
  assign t_cd_p11 = C1 & D1;
  assign _006_ = t_cd_p00 ^ t_cd_p01;
  assign t_cd0 = _006_ ^ r1;
  assign _007_ = t_cd_p11 ^ t_cd_p10;
  assign t_cd1 = _007_ ^ r1;
  assign b_p00 = t_cd0 & E0;
  assign b_p01 = t_cd0 & E1;
  assign b_p10 = t_cd1 & E0;
  assign b_p11 = t_cd1 & E1;
  assign _008_ = b_p00 ^ b_p01;
  assign b_w0 = _008_ ^ r2;
  assign _009_ = b_p11 ^ b_p10;
  assign b_w1 = _009_ ^ r2;
  assign t_fg_p00 = F0 & G0;
  assign t_fg_p01 = F0 & G1;
  assign t_fg_p10 = F1 & G0;
  assign t_fg_p11 = F1 & G1;
  assign _010_ = t_fg_p00 ^ t_fg_p01;
  assign t_fg0 = _010_ ^ r3;
  assign _011_ = t_fg_p11 ^ t_fg_p10;
  assign t_fg1 = _011_ ^ r3;
  assign c_p00 = t_fg0 & H0;
  assign c_p01 = t_fg0 & H1;
  assign c_p10 = t_fg1 & H0;
  assign c_p11 = t_fg1 & H1;
  assign _012_ = c_p00 ^ c_p01;
  assign c_w0 = _012_ ^ r4;
  assign _013_ = c_p11 ^ c_p10;
  assign c_w1 = _013_ ^ r4;
  assign d_p00 = I0 & J0;
  assign d_p01 = I0 & J1;
  assign d_p10 = I1 & J0;
  assign d_p11 = I1 & J1;
  assign _014_ = d_p00 ^ d_p01;
  assign d_w0 = _014_ ^ r5;
  assign _015_ = d_p11 ^ d_p10;
  assign d_w1 = _015_ ^ r5;
  assign and_ab_p00 = a_w0 & b_w0;
  assign and_ab_p01 = a_w0 & b_w1;
  assign and_ab_p10 = a_w1 & b_w0;
  assign and_ab_p11 = a_w1 & b_w1;
  assign _016_ = and_ab_p00 ^ and_ab_p01;
  assign and_ab0 = _016_ ^ r6;
  assign _017_ = and_ab_p11 ^ and_ab_p10;
  assign and_ab1 = _017_ ^ r6;
  assign _018_ = a_w0 ^ b_w0;
  assign or1_0 = _018_ ^ and_ab0;
  assign _019_ = a_w1 ^ b_w1;
  assign or1_1 = _019_ ^ and_ab1;
  assign and_or1c_p00 = or1_0 & c_w0;
  assign and_or1c_p01 = or1_0 & c_w1;
  assign and_or1c_p10 = or1_1 & c_w0;
  assign and_or1c_p11 = or1_1 & c_w1;
  assign _020_ = and_or1c_p00 ^ and_or1c_p01;
  assign and_or1c0 = _020_ ^ r7;
  assign _021_ = and_or1c_p11 ^ and_or1c_p10;
  assign and_or1c1 = _021_ ^ r7;
  assign _022_ = or1_0 ^ c_w0;
  assign or2_0 = _022_ ^ and_or1c0;
  assign _023_ = or1_1 ^ c_w1;
  assign or2_1 = _023_ ^ and_or1c1;
  assign and_or2d_p00 = or2_0 & d_w0;
  assign and_or2d_p01 = or2_0 & d_w1;
  assign and_or2d_p10 = or2_1 & d_w0;
  assign and_or2d_p11 = or2_1 & d_w1;
  assign _000_ = and_or2d_p00 ^ and_or2d_p01;
  assign and_or2d0 = _000_ ^ r8;
  assign _001_ = and_or2d_p11 ^ and_or2d_p10;
  assign and_or2d1 = _001_ ^ r8;
  assign _002_ = or2_0 ^ d_w0;
  assign X_w0 = _002_ ^ and_or2d0;
  assign _003_ = or2_1 ^ d_w1;
  assign X1 = _003_ ^ and_or2d1;
  assign X0 = X_w0;
  assign XBAR1 = X1;
  assign X_w1 = X1;
endmodule

module circuit(clk, A0, A1, B0, B1, C0, C1, D0, D1, E0, E1, F0, F1, G0, G1, H0, H1, I0, I1, J0, J1, r0, r1, r2, r3, r4, r5, r6, r7, r8, X0, X1, XBAR0, XBAR1);
  input A0;
  input A1;
  input B0;
  input B1;
  input C0;
  input C1;
  input D0;
  input D1;
  input E0;
  input E1;
  input F0;
  input F1;
  input G0;
  input G1;
  input H0;
  input H1;
  input I0;
  input I1;
  input J0;
  input J1;
  output X0;
  wire X0_w;
  output X1;
  wire X1_w;
  output XBAR0;
  wire XBAR0_w;
  output XBAR1;
  wire XBAR1_w;
  input clk;
  input r0;
  input r1;
  input r2;
  input r3;
  input r4;
  input r5;
  input r6;
  input r7;
  input r8;
  DFF _0_ (
    .C(clk),
    .D(X1_w),
    .Q(X1)
  );
  DFF _1_ (
    .C(clk),
    .D(XBAR0_w),
    .Q(XBAR0)
  );
  DFF _2_ (
    .C(clk),
    .D(XBAR1_w),
    .Q(XBAR1)
  );
  DFF _3_ (
    .C(clk),
    .D(X0_w),
    .Q(X0)
  );
  EXP_GATE_3_masked dut (
    .A0(A0),
    .A1(A1),
    .B0(B0),
    .B1(B1),
    .C0(C0),
    .C1(C1),
    .D0(D0),
    .D1(D1),
    .E0(E0),
    .E1(E1),
    .F0(F0),
    .F1(F1),
    .G0(G0),
    .G1(G1),
    .H0(H0),
    .H1(H1),
    .I0(I0),
    .I1(I1),
    .J0(J0),
    .J1(J1),
    .X0(X0_w),
    .X1(X1_w),
    .XBAR0(XBAR0_w),
    .XBAR1(XBAR1_w),
    .r0(r0),
    .r1(r1),
    .r2(r2),
    .r3(r3),
    .r4(r4),
    .r5(r5),
    .r6(r6),
    .r7(r7),
    .r8(r8)
  );
endmodule
